stages:
  - dependencies
  - build
  - deploy

install_dependenices:
  image: node:8.9-alpine
  stage: dependencies
  script:
    - npm i
  artifacts:
    untracked: true

build:
  image: node:8.9-alpine
  stage: build
  dependencies:
    - install_dependenices
  script:
    - npm run build:live
  artifacts:
    paths:
      - dist

deploy:
  image: alpine:3.18
  stage: deploy
  dependencies:
    - build
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_PROD" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $SSH_IP_PROD >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - cd dist
    - scp -r * $SSH_USER_PROD@$SSH_IP_PROD:$SSH_PATH_PROD
